### PR TITLE
feat: add multiple exports in esbuild

### PR DESCRIPTION
**Pull request by tonycaputome**
- add example with runnable example
- move test folder outside src
- run prettier before build script
- other minor changes

### CODE REVIEW

**Review by Cadienvan — CHANGES_REQUESTED** [review]
I get moving tests to another folder and providing some examples, yet I don't get the CJS + ESM part as the current build method makes a single file both importable via CJS and ESM. If you could just remove or explain such part we can merge it.

**Comment by tonycaputome** [comment]
With the CommonJS format you can supprt multiple versions of NodeJS even the oldest, and you can run the library without any transpiling process or without any extra agument like `--experimental-module`
Using only ESM module forcing the library user to add an additional code transformation as an example with Babel.
With this setup you provide more options to the user.

**Comment by tonycaputome** [comment]
https://antfu.me/posts/publish-esm-and-cjs#compatibility

**Comment by Cadienvan** [comment]
I just tried building a new npm project using Node v14.16.0 and didn't have any issues requiring in a .js file and importing in a .mjs file, considering Node 14 is the oldest LTS it doesn't seem worth to me having two builds to support non-LTS Node versions. Am I missing something?

**Comment by tonycaputome** [comment]
It's up to you, you can close this PR.

**Comment by Cadienvan** [comment]
I'm just trying to understand the effective need of this specific request.
If all LTS versions are supported and no benefit is given having two built files instead of one, why should we go for it?

By the way, all the other things done in the PR are suitable to be merged, so if you can just fall back to the initial implementation of the build I can merge it.

**Comment by tonycaputome** [comment]
I am driving now 😂

**Comment by tonycaputome** [comment]
So I'll give you a practical example of why you should support also a cjs module.
There are legacy systems that doesn't care or follow the LTS versions they are stuck in a particular version.
In my current company, part of our business is sold documents that are created with two libraries for manipulate Excel and pdf files.
We can't upgrade the Node version (14.3.0) because these external libraries are not supported and we also can't rename our files to .mjs due the pipeline flow.
There are thousands of situation like that and you don't know where your library will be used.
That said my PR wasn't a real request but just an advice. As I am on my mobile I'll modify the PR in the following days.

Your library at the moment cannot be included anywhere like in an expressjs or another project and again my PR was an `advice` 😉😉😉😉

I am agree with you that there's an additional bundling step, but it's a machine resource thing it doesn't cost you nothing just some ms of transpiling.

**Comment by Cadienvan** [comment]
I get your point, and I'd really love to include every possible use case, yet moving to a previous version would need much more work and transpiling as many features wouldn't be available anyway.

As an example, moving to node 12.22 wouldn't allow the library to run in its current state.

Moving outside of LTS would need too much effort.

**Comment by tonycaputome** [comment]
@Cadienvan please check the changes.

**Pull request merged**
